#!/bin/bash

if [[ -n $(pgrep Xephyr) ]]; then
  echo "Xephyr is running"
  kill -s kill "$(ps -C "Xephyr" -o pid=)"
else
  echo "Xephyr is not running"
  Xephyr :1 -ac -screen 2560x1600 &
  sleep 0.1
  DISPLAY=:1 awesome -c "$HOME"/terminalConfigs/.dotfiles/awesome/rc-dev.lua
fi
